blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/WVFNWEvuqX
    about: Report an issue on our official Discord!
  - name: SpigotMC Page
    url: https://www.spigotmc.org/resources/plutochat.99282/
    about: Read more about PlutoChat!